# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OA_WebMap_Updater
                                 A QGIS plugin
 Updater for OA Webmap
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-20
        copyright            : (C) 2021 by VP
        email                : pinnavalerio@yahoo.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OA_WebMap_Updater class from file OA_WebMap_Updater.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OA_WebMap_Updater import OA_WebMap_Updater
    return OA_WebMap_Updater(iface)
